export default {
  'name': 'all',
  'abstract': true,
  'acl': 100,
  'entities': [
    'Student',
    'Curator',
    'Group',
    'Person',
    'User',
    'SocialNetwork',
    'SocialNetworkType',
    'Phone',
    'PhoneType',
    'Email',
    'EmailType',
    'StudentAttendance',
    'Meeting',
    'Subject',
    'Course',
    'SubjectCourse',
  ],
  'mutations': [],
};
